# generated by `pklith gen` from .pklith; do not edit
# The packages the generated hk steps run: `import ./nix/pklith.nix catalog`,
# with pklith's catalog namespace (nixpkgs plus the tools nixpkgs lacks).
catalog: [
  catalog.actionlint
  catalog.cargo
  catalog.cargo-deny
  catalog.cargo-nextest
  catalog.clippy
  catalog.jq
  catalog.lychee
  catalog.microlith
  catalog.nix
  catalog.nixfmt
  catalog.ripsecrets
  catalog.rustfmt
  catalog.shellcheck
  catalog.sherd
  catalog.taplo
  catalog.typos
  catalog.zizmor
]
