//! `pkli gen`, run against the built binary.

mod common;

use common::{OK, Result, pkli, repo, temp};
use std::path::Path;

const GENERATED: &str = "// generated by `pkli gen` from .pklith; do not edit\nimport \"pkl/Config.pkl\"\n\nsteps: Mapping<String, Config.Step> = new {\n  [\"lint\"] {\n    glob = List(\"*\")\n    check = \"true || { echo 'lint: m' >&2; exit 1; }\"\n  }\n}\n\npush: Mapping<String, Config.Step> = new {\n}\n";

fn read_only(path: &Path, on: bool) -> Result {
    let mut permissions = std::fs::metadata(path)?.permissions();
    permissions.set_readonly(on);
    Ok(std::fs::set_permissions(path, permissions)?)
}

/// gen writes hk.pklith.pkl, and a second run writes nothing (gen V2): the
/// file is read-only by then, so any write would fail the run.
#[test]
fn gen_writes_once_and_then_leaves_the_file_alone() -> Result {
    let dir = repo("gen", Some(OK))?;
    assert_eq!(
        pkli(&dir, &["gen"])?,
        (Some(0), String::new(), String::new())
    );
    let file = dir.join("hk.pklith.pkl");
    assert_eq!(std::fs::read_to_string(&file)?, GENERATED);
    read_only(&file, true)?;
    assert_eq!(pkli(&dir, &["gen"])?.0, Some(0));
    read_only(&file, false)?;
    Ok(std::fs::remove_dir_all(dir)?)
}

/// gen V3: `--check` passes on a fresh file and fails on an edited or
/// missing one, writing nothing.
#[test]
fn gen_check_fails_on_a_stale_or_missing_file() -> Result {
    let dir = repo("gen-check", Some(OK))?;
    let stale = (
        Some(1),
        String::new(),
        "pkli gen: hk.pklith.pkl is stale; run `pkli gen` and stage it\n".to_owned(),
    );
    assert_eq!(pkli(&dir, &["gen", "--check"])?, stale);
    pkli(&dir, &["gen"])?;
    assert_eq!(pkli(&dir, &["gen", "--check"])?.0, Some(0));
    std::fs::write(dir.join("hk.pklith.pkl"), "edited\n")?;
    assert_eq!(pkli(&dir, &["gen", "--check"])?, stale);
    Ok(std::fs::remove_dir_all(dir)?)
}

/// A stale file that cannot be written exits 2 naming it.
#[test]
fn gen_cannot_write_exits_2() -> Result {
    let dir = repo("gen-readonly", Some(OK))?;
    let file = dir.join("hk.pklith.pkl");
    std::fs::write(&file, "old\n")?;
    read_only(&file, true)?;
    let (code, _, stderr) = pkli(&dir, &["gen"])?;
    read_only(&file, false)?;
    assert_eq!(code, Some(2));
    assert!(
        stderr.starts_with("pkli gen: cannot write hk.pklith.pkl: "),
        "{stderr}"
    );
    Ok(std::fs::remove_dir_all(dir)?)
}

/// No registry, or no repository, exits 2 naming the cause.
#[test]
fn gen_without_a_registry_or_repository_exits_2() -> Result {
    let dir = repo("gen-missing", None)?;
    assert!(
        pkli(&dir, &["gen"])?
            .2
            .starts_with("pkli gen: cannot read ")
    );
    let outside = temp("gen-outside")?;
    assert_eq!(
        pkli(&outside, &["gen", "--check"])?.2,
        "pkli gen: not inside a git repository; pass --root DIR\n"
    );
    std::fs::remove_dir_all(outside)?;
    Ok(std::fs::remove_dir_all(dir)?)
}

/// Catalog T2: a `.pklith` with no `## checks` section names built-in
/// checks, and gen renders them from the catalog compiled into `pkli`.
#[test]
fn gen_renders_a_builtin_check_the_registry_never_defines() -> Result {
    let registry = "format 1\n## types\ntype|checks|min|exempt\nsh|shellcheck|-|-\n";
    let dir = repo("gen-builtin", Some(registry))?;
    assert_eq!(pkli(&dir, &["gen"])?.0, Some(0));
    let text = std::fs::read_to_string(dir.join("hk.pklith.pkl"))?;
    assert!(text.contains("[\"shellcheck\"]"), "{text}");
    assert!(text.contains("shellcheck {{files}}"), "{text}");
    Ok(std::fs::remove_dir_all(dir)?)
}

/// Two used checks, so a file can hold one of them the way `pkli lay`
/// writes it partway through.
const TWO: &str = "format 1\n## checks\nid|category|nix|glob|check|fix|env|msg\nlint|lint|-|*|true|-|-|m\nfmt|format|-|*|true|-|-|m\n## types\ntype|checks|min|exempt\nrs|lint,fmt|-|-\npklith|-|-|the registry itself\npkl|-|-|hk config\n";

/// gen V3: `--check` judges the steps the module holds. Files with only
/// some of the used checks, as `pkli lay` leaves it between commits, is
/// fresh (the missing ones are `pkli check`'s gap); a held step that no
/// longer matches its row is stale.
#[test]
fn gen_check_judges_only_the_steps_the_file_holds() -> Result {
    let dir = repo("gen-partial", Some(TWO))?;
    let registry = pklith::registry::parse(TWO)?;
    let catalog = pklith::catalog::parse(&registry.checks)?;
    let used = pklith::r#gen::used(&registry, &catalog);
    pklith::r#gen::write(&dir, used.get(..1).unwrap_or_default())?;
    let partial = std::fs::read_to_string(dir.join("hk.pklith.pkl"))?;
    assert_eq!(pkli(&dir, &["gen", "--check"])?.0, Some(0));
    std::fs::write(
        dir.join("hk.pklith.pkl"),
        partial.replace("true ||", "false ||"),
    )?;
    assert_eq!(pkli(&dir, &["gen", "--check"])?.0, Some(1));
    Ok(std::fs::remove_dir_all(dir)?)
}

/// Every verb resolves the whole registry: gen refuses a local fragment
/// naming an unknown check, as check and detect do.
#[test]
fn gen_refuses_a_bad_local_fragment() -> Result {
    let bad = format!("{OK}## fragments\nfragment|triggers|checks|seed\nx|always|nope|-\n");
    let dir = repo("gen-bad-fragment", Some(&bad))?;
    let (code, _, stderr) = pkli(&dir, &["gen"])?;
    assert_eq!(
        (code, stderr.as_str()),
        (
            Some(2),
            "pkli gen: .pklith:12: fragment `x` names unknown check `nope`\n"
        )
    );
    assert!(!dir.join("hk.pklith.pkl").exists());
    Ok(std::fs::remove_dir_all(dir)?)
}

/// Gen T2: gen writes nix/pklith.nix beside the module, and `--check`
/// names it when it drifts.
#[test]
fn gen_writes_and_checks_the_nix_list() -> Result {
    let dir = repo("gen-nix", Some(TWO))?;
    assert_eq!(pkli(&dir, &["gen"])?.0, Some(0));
    let nix = std::fs::read_to_string(dir.join("nix/pklith.nix"))?;
    assert!(nix.ends_with("catalog: [ ]\n"), "{nix}");
    std::fs::write(dir.join("nix/pklith.nix"), "edited\n")?;
    let (code, _, stderr) = pkli(&dir, &["gen", "--check"])?;
    assert_eq!(
        (code, stderr.as_str()),
        (
            Some(1),
            "pkli gen: nix/pklith.nix is stale; run `pkli gen` and stage it\n"
        )
    );
    Ok(std::fs::remove_dir_all(dir)?)
}
