//! The coverage matrix as Markdown (report T3): a drop-in for a legacy
//! `docs/linter-coverage.md`. Its table keeps the legacy reading (root
//! R3): the first column's backticked tokens are the types, and `-` in the
//! second marks an exemption whose reason is in the third.

use super::Verdict;

/// The matrix: one row per declared type in registry order (V1), the
/// universal checks below it.
#[must_use]
pub fn render(v: &Verdict<'_>) -> String {
    let rows: String = v.coverage.covered.iter().map(row).collect();
    let universal = v.universal.join(", ");
    format!(
        "# Linter coverage\n\nGenerated by `pklith report --format md` from .pklith; do not edit.\n\n| Type | Checks | Notes |\n|---|---|---|\n{rows}\nEvery type also gets: {universal}.\n"
    )
}

/// One declared type: its checks and file count, or `-` and the reason.
fn row(c: &crate::cover::Covered) -> String {
    let (checks, notes) = match &c.exempt {
        Some(reason) => ("-".to_owned(), reason.clone()),
        None => (c.checks.join(", "), files(c.files)),
    };
    format!("| `{}` | {checks} | {notes} |\n", legacy(&c.key))
}

/// Legacy tools read `.rs`: an extension gets its dot back; a whole name
/// (`Cargo.lock`, `justfile`) or a path class stays as written.
fn legacy(key: &str) -> String {
    if key.contains(['.', ':', '/']) || key.chars().any(char::is_uppercase) {
        key.to_owned()
    } else {
        format!(".{key}")
    }
}

fn files(n: usize) -> String {
    if n == 1 {
        "1 file".to_owned()
    } else {
        format!("{n} files")
    }
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::cover::judge;
    use crate::registry::{Error, parse};

    const REGISTRY: &str = "format 1\n## types\ntype|checks|min|exempt\n*|typos|-|-\nrs|clippy, rustfmt|-|-\nCargo.lock|-|-|generated by cargo\ntoml|taplo|-|-\n";

    fn rendered() -> Result<String, Error> {
        let files = ["a.rs", "b.rs", "Cargo.lock", "c.toml"].map(str::to_owned);
        let coverage = judge(&files, &parse(REGISTRY)?);
        let universal = ["typos".to_owned()];
        Ok(render(&super::Verdict {
            coverage: &coverage,
            unbacked: &[],
            universal: &universal,
        }))
    }

    /// V1: registry order, legacy type tokens, exemptions as `-` with
    /// their reason, the universal checks below.
    #[test]
    fn the_matrix_lists_each_type_in_registry_order() -> Result<(), Error> {
        let text = rendered()?;
        let rows =
            "| `.rs` | clippy, rustfmt | 2 files |\n| `Cargo.lock` | - | generated by cargo |\n";
        assert!(text.contains(rows), "{text}");
        assert!(text.ends_with("Every type also gets: typos.\n"));
        Ok(())
    }

    /// Drop-in: the legacy importer reads the types back.
    #[test]
    fn the_legacy_importer_reads_it_back() -> Result<(), Error> {
        let tokens = crate::legacy::tokens(&rendered()?);
        let keys: Vec<&str> = tokens.iter().map(|t| t.key.as_str()).collect();
        assert_eq!(keys, ["rs", "Cargo.lock", "toml"]);
        Ok(())
    }
}
