//! The README badge block, and the numbers `docs/LLM-DISCLAIMER.md` quotes
//! in prose. One set of facts renders both, so a badge's alt text, its URL
//! and a sentence cannot disagree.

use crate::facts::{Nixpkgs, Platform};

/// Everything the badges say, each read from the file that owns it.
#[derive(Debug)]
pub struct Facts {
    /// `owner/repo`, from Cargo.toml's `repository`.
    pub slug: String,
    /// Cargo.toml's `license`, `edition` and `rust-version`.
    pub license: String,
    /// The Rust edition.
    pub edition: String,
    /// The minimum supported Rust version.
    pub msrv: String,
    /// Entries in Cargo.toml's `[dependencies]`.
    pub dependencies: usize,
    /// `.coverage`'s floor, as a percentage without trailing zeros.
    pub floor: String,
    /// Steps in hk.pkl's pre-commit and pre-push hooks.
    pub steps: (usize, usize),
    /// `§V` rows, `§B` rows and `SPEC.md` files across the federation.
    pub spec: (usize, usize, usize),
    /// The locked nixpkgs.
    pub nixpkgs: Nixpkgs,
    /// What CI's matrix builds on.
    pub platforms: Vec<Platform>,
}

impl Facts {
    /// Refuse a fact that reads empty or zero: a badge is not worth a
    /// guessed number (dev V1).
    ///
    /// # Errors
    ///
    /// The first fact that is empty or zero, named.
    pub fn checked(self) -> Result<Self, String> {
        let empty = [
            ("Cargo.toml repository", self.slug.is_empty()),
            ("Cargo.toml license", self.license.is_empty()),
            ("Cargo.toml edition", self.edition.is_empty()),
            ("Cargo.toml rust-version", self.msrv.is_empty()),
            ("Cargo.toml [dependencies]", self.dependencies == 0),
            ("hk.pkl steps", self.steps.0 == 0 || self.steps.1 == 0),
            ("SPEC.md rows", self.spec.0 == 0 || self.spec.2 == 0),
            ("ci.yml platforms", self.platforms.is_empty()),
        ];
        match empty.iter().find(|(_, is)| *is) {
            Some((what, _)) => Err(format!("{what} read empty or zero; fix the source")),
            None => Ok(self),
        }
    }
}

/// The block. `{name}` is a fact as written, `{name|url}` the same fact
/// escaped for a shields.io path, so a badge's alt text and its URL come
/// from one value and cannot disagree. The credits stay literal: they name
/// what built this repository, which every commit's trailer records.
const TEMPLATE: &str = "<!-- BEGIN badges: generated by `cargo run -p pklith-dev -- readme`; do not edit -->
[![CI](https://github.com/{slug}/actions/workflows/ci.yml/badge.svg)](https://github.com/{slug}/actions/workflows/ci.yml)
[![License: {license}](https://img.shields.io/badge/license-{license|url}-blue.svg)](LICENSE)
[![edition {edition}](https://img.shields.io/badge/edition-{edition|url}-000000?logo=rust&logoColor=white)](Cargo.toml)
[![MSRV {msrv}](https://img.shields.io/badge/MSRV-{msrv|url}-000000?logo=rust&logoColor=white)](Cargo.toml)
[![direct dependencies {deps}](https://img.shields.io/badge/direct_dependencies-{deps|url}-brightgreen)](docs/THIRD-PARTY-NOTICES.md)
[![unsafe forbidden](https://img.shields.io/badge/unsafe-forbidden-brightgreen)](Cargo.toml)
[![network pkli protect only](https://img.shields.io/badge/network-pkli_protect_only-brightgreen)](docs/SECURITY.md)

[![gate hk](https://img.shields.io/badge/gate-hk-6E4AFF)](hk.pkl)
[![gate steps {steps}](https://img.shields.io/badge/gate_steps-{steps|url}-6E4AFF)](hk.pkl)
[![coverage floor {floor}%](https://img.shields.io/badge/coverage_floor-%E2%89%A5{floor|url}%25-brightgreen)](.coverage)
[![invariants {inv}](https://img.shields.io/badge/invariants-{inv|url}-6E4AFF)](SPEC.md)
[![bugs logged {bugs}](https://img.shields.io/badge/bugs_logged-{bugs|url}-6E4AFF)](SPEC.md)
[![federated nodes {nodes}](https://img.shields.io/badge/federated_nodes-{nodes|url}-6E4AFF)](SPEC.md)

[![nix flake](https://img.shields.io/badge/nix-flake-5277C3?logo=nixos&logoColor=white)](flake.nix)
[![nixpkgs {nixpkgs}](https://img.shields.io/badge/nixpkgs-{nixpkgs|url}-5277C3?logo=nixos&logoColor=white)](flake.lock)
{platforms}
[![built with Claude Code](https://img.shields.io/badge/built_with-Claude_Code-D97757)](https://claude.com/claude-code)
[![built with Opus 5.5](https://img.shields.io/badge/built_with-Opus_5.5-D97757)](https://www.anthropic.com/claude)
[![built with SDD](https://img.shields.io/badge/built_with-spec--driven_development-D97757)](SPEC.md)
<!-- END badges -->
";

/// shields.io path text: `-` doubles, a space is `_`, and these encode.
fn esc(text: &str) -> String {
    text.replace('-', "--")
        .replace('%', "%25")
        .replace('+', "%2B")
        .replace('/', "%2F")
        .replace(' ', "_")
}

/// The block, markers included.
#[must_use]
pub fn render(f: &Facts) -> String {
    let values = f.cargo().into_iter().chain(f.gate());
    let filled = values.fold(TEMPLATE.to_owned(), |text, (name, value)| {
        text.replace(&format!("{{{name}|url}}"), &esc(&value))
            .replace(&format!("{{{name}}}"), &value)
    });
    filled.replace("{platforms}\n", &platforms(&f.platforms))
}

impl Facts {
    /// The template's Cargo.toml facts, by name.
    fn cargo(&self) -> [(&'static str, String); 5] {
        [
            ("slug", self.slug.clone()),
            ("license", self.license.clone()),
            ("edition", self.edition.clone()),
            ("msrv", self.msrv.clone()),
            ("deps", self.dependencies.to_string()),
        ]
    }

    /// The template's gate, spec and nix facts, by name.
    fn gate(&self) -> [(&'static str, String); 6] {
        let (n, (inv, bugs, nodes)) = (&self.nixpkgs, self.spec);
        let steps = format!("{} commit / {} push", self.steps.0, self.steps.1);
        [
            ("steps", steps),
            ("floor", self.floor.clone()),
            ("inv", inv.to_string()),
            ("bugs", bugs.to_string()),
            ("nodes", nodes.to_string()),
            ("nixpkgs", format!("{} ({} - {})", n.series, n.day, n.rev)),
        ]
    }
}

/// One badge per platform CI builds on, then the blank line before the
/// credits.
fn platforms(list: &[Platform]) -> String {
    let line = |(arch, os): &Platform| {
        format!(
            "[![{arch} {os}](https://img.shields.io/badge/{os}-5277C3?logo={arch}&logoColor=white)](.github/workflows/ci.yml)\n"
        )
    };
    list.iter().map(line).collect::<String>() + "\n"
}

/// The disclaimer's quoted numbers that no longer match the facts. Its
/// lines wrap, so the text is joined before matching.
#[must_use]
pub fn stale_prose(disclaimer: &str, f: &Facts) -> Vec<String> {
    let prose = disclaimer.split_whitespace().collect::<Vec<_>>().join(" ");
    let (inv, bugs, _) = f.spec;
    [
        format!("**{} steps on commit, {} on push**", f.steps.0, f.steps.1),
        format!("**{inv} `§V` invariants**"),
        format!("**{bugs} `§B` bugs**"),
        format!("floor of {}%", f.floor),
    ]
    .into_iter()
    .filter(|want| !prose.contains(want.as_str()))
    .collect()
}

#[cfg(test)]
mod tests;
