//! `pklith-dev catalog [--check]`: the tables in docs/CATALOG.md, from the
//! built-in catalog pklith compiles in, read through pklith's own parsers.

use crate::io::{Failed, read};
use pklith::catalog::Check;
use pklith::registry::Row;
use std::fmt::Write as _;

const SOURCE: &str = "src/catalog/builtin.pklith";
const DOC: &str = "docs/CATALOG.md";

/// `a, b` as `` `a` `b` ``; nothing as `none`.
fn code(items: &[String], none: &str) -> String {
    if items.is_empty() {
        return none.to_owned();
    }
    let spans: Vec<String> = items.iter().map(|i| format!("`{i}`")).collect();
    spans.join(" ")
}

/// One check as a table row; a pipe in its message stays escaped.
fn check_row(c: &Check) -> String {
    let nix = if c.nix.is_empty() {
        "hk built-in".to_owned()
    } else {
        format!("`{}`", c.nix)
    };
    let fixes = if c.fix.is_some() { "yes" } else { "-" };
    let (globs, msg) = (code(&c.globs, "whole tree"), c.msg.replace('|', "\\|"));
    format!(
        "| `{}` | {} | {nix} | {globs} | {fixes} | {msg} |\n",
        c.id,
        c.category.name()
    )
}

/// Cell `i` of `row` as a comma list, as code spans; `-` when empty.
fn listed(row: &Row, i: usize) -> String {
    let cell = row.cells.get(i).map_or("", String::as_str);
    let items: Vec<String> = cell
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect();
    code(&items, "-")
}

/// One fragment row (`fragment|triggers|checks|seed`) as a table row.
fn fragment_row(row: &Row) -> String {
    let cell = |i: usize| row.cells.get(i).map_or("", String::as_str);
    let always = cell(1) == "always";
    let on = if always {
        "every repository".to_owned()
    } else {
        listed(row, 1)
    };
    let (checks, seeds) = (listed(row, 2), listed(row, 3));
    format!("| `{}` | {on} | {checks} | {seeds} |\n", cell(0))
}

/// The tables block, markers included.
#[must_use]
pub fn render(checks: &[Check], fragments: &[Row]) -> String {
    let mut out = String::from(
        "<!-- BEGIN catalog: generated by `cargo run -p pklith-dev -- catalog` from src/catalog/builtin.pklith; do not edit -->\n### Checks\n\n| check | category | nix package | runs on | fixes | fails when |\n|---|---|---|---|---|---|\n",
    );
    for c in checks {
        out.push_str(&check_row(c));
    }
    let _ = write!(
        out,
        "\n### Fragments\n\n| fragment | switched on by | checks | seeds |\n|---|---|---|---|\n"
    );
    for f in fragments {
        out.push_str(&fragment_row(f));
    }
    out + "<!-- END catalog -->\n"
}

/// Render or check.
///
/// # Errors
///
/// Drift (1), an unreadable or invalid catalog, or no block (2).
pub fn run_verb(check: bool) -> Result<(), Failed> {
    let invalid = |e: pklith::registry::Error| (2, format!("{SOURCE}: {e}"));
    let registry = pklith::registry::parse(&read(SOURCE)?).map_err(invalid)?;
    let checks = pklith::catalog::parse(&registry.checks).map_err(invalid)?;
    let block = render(&checks, &registry.fragments);
    let wanted = crate::block::splice(&read(DOC)?, "catalog", &block)
        .ok_or((2, format!("{DOC} has no <!-- BEGIN catalog --> block")))?;
    crate::io::update(DOC, &wanted, check, "catalog")
}

#[cfg(test)]
mod tests {
    use super::render;

    const CATALOG: &str = "format 1\n## checks\nid|category|nix|glob|check|fix|env|msg\nws|hygiene|-|**/*|c|f|-|trailing \\| blanks\nsc|lint|shellcheck|-|c|-|-|finding\n## fragments\nfragment|triggers|checks|seed\nbase|always|ws|readme\nshell|**/*.sh, **/*.bash|sc|-\n";

    #[test]
    fn the_catalog_becomes_two_tables() -> Result<(), Box<dyn std::error::Error>> {
        let registry = pklith::registry::parse(CATALOG)?;
        let checks = pklith::catalog::parse(&registry.checks)?;
        let got = render(&checks, &registry.fragments);
        for want in [
            "| `ws` | hygiene | hk built-in | `**/*` | yes | trailing \\| blanks |\n",
            "| `sc` | lint | `shellcheck` | whole tree | - | finding |\n",
            "| `base` | every repository | `ws` | `readme` |\n",
            "| `shell` | `**/*.sh` `**/*.bash` | `sc` | - |\n<!-- END catalog -->\n",
        ] {
            assert!(got.contains(want), "missing {want} in {got}");
        }
        Ok(())
    }
}
