//! `pklith-dev cli [--check]`: the usage block in docs/CLI.md is the text
//! `pkli` prints, taken from `pklith::cli::USAGE`, so the page cannot
//! describe a flag the binary lacks.

use crate::io::{Failed, read};

const DOC: &str = "docs/CLI.md";

/// The usage block, markers included.
#[must_use]
pub fn render(usage: &str) -> String {
    format!(
        "<!-- BEGIN usage: generated by `cargo run -p pklith-dev -- cli` from pkli's usage text; do not edit -->\n```text\n{}\n```\n<!-- END usage -->\n",
        usage.trim_end()
    )
}

/// Render or check.
///
/// # Errors
///
/// Drift (1), an unreadable doc or no block (2).
pub fn run_verb(check: bool) -> Result<(), Failed> {
    let wanted = crate::block::splice(&read(DOC)?, "usage", &render(pklith::cli::USAGE))
        .ok_or((2, format!("{DOC} has no <!-- BEGIN usage --> block")))?;
    crate::io::update(DOC, &wanted, check, "cli")
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_usage_is_fenced_verbatim() {
        let got = super::render("usage: pkli\n\n  check\n");
        assert!(
            got.ends_with("```text\nusage: pkli\n\n  check\n```\n<!-- END usage -->\n"),
            "{got}"
        );
    }
}
