//! `pklith-dev notices [--check]`: the crate table in
//! `docs/THIRD-PARTY-NOTICES.md`, from what `Cargo.lock` resolves on normal
//! dependency edges, and the prose around it held to the table.

use crate::io::{Failed, read, run};
use std::fmt::Write as _;

const DOC: &str = "docs/THIRD-PARTY-NOTICES.md";

/// A crate pklith ships: name, version, licence.
pub type Crate = (String, String, String);

/// The crates in `cargo tree -f '{p}|{l}' --prefix none` output, sorted
/// and once each, without pklith itself.
#[must_use]
pub fn crates(tree: &str) -> Vec<Crate> {
    let mut found: Vec<Crate> = tree.lines().filter_map(parse).collect();
    found.sort();
    found.dedup();
    found
}

/// One `name vX.Y.Z (path)|licence` line.
fn parse(line: &str) -> Option<Crate> {
    let (package, licence) = line.split_once('|')?;
    let mut words = package.split_whitespace();
    let (name, version) = (words.next()?, words.next()?.strip_prefix('v')?);
    // cargo marks a crate it already printed with `(*)`, after the licence.
    let licence = licence.trim().trim_end_matches("(*)").trim_end();
    let own = (name.to_owned(), version.to_owned(), licence.to_owned());
    (name != "pklith").then_some(own)
}

/// The table block, markers included.
#[must_use]
pub fn table(crates: &[Crate]) -> String {
    let mut out = String::from(
        "<!-- BEGIN crates: generated by `cargo run -p pklith-dev -- notices` from Cargo.lock; do not edit -->\n| Crate | Version | Licence |\n|---|---|---|\n",
    );
    for (name, version, licence) in crates {
        let _ = writeln!(out, "| {name} | {version} | {licence} |");
    }
    out + "<!-- END crates -->\n"
}

/// The first sentence's claim for `direct` dependencies and `total` crates.
fn claim(direct: usize, total: usize) -> String {
    let noun = if direct == 1 {
        "dependency"
    } else {
        "dependencies"
    };
    format!("**{direct} direct {noun}**, which pulls in {total} crates")
}

/// What the prose claims that the table does not bear out: the direct and
/// total counts in its first sentence, and that every crate is under MIT.
#[must_use]
pub fn stale_prose(doc: &str, direct: usize, crates: &[Crate]) -> Vec<String> {
    let prose = doc.split_whitespace().collect::<Vec<_>>().join(" ");
    let claim = claim(direct, crates.len());
    let wrong_count = (!prose.contains(&claim)).then(|| format!("{DOC} must say {claim}"));
    let not_mit = crates.iter().filter(|(_, _, l)| !l.contains("MIT"));
    let wrong_licence =
        not_mit.map(|(n, _, l)| format!("{n} is {l}, not available under MIT as {DOC} says"));
    wrong_count.into_iter().chain(wrong_licence).collect()
}

const TREE: [&str; 11] = [
    "tree",
    "-p",
    "pklith",
    "-e",
    "normal",
    "--prefix",
    "none",
    "-f",
    "{p}|{l}",
    "--locked",
    "--offline",
];

/// Render or check.
///
/// # Errors
///
/// Stale prose or drift (1), cargo or a file failing (2).
pub fn run_verb(check: bool) -> Result<(), Failed> {
    let crates = crates(&run("cargo", &TREE)?);
    if crates.is_empty() {
        return Err((2, "cargo tree listed no dependencies".to_owned()));
    }
    let (doc, direct) = (read(DOC)?, crate::facts::dependencies(&read("Cargo.toml")?));
    if let Some(stale) = stale_prose(&doc, direct, &crates).into_iter().next() {
        return Err((1, stale));
    }
    let wanted = crate::block::splice(&doc, "crates", &table(&crates))
        .ok_or((2, format!("{DOC} has no <!-- BEGIN crates --> block")))?;
    crate::io::update(DOC, &wanted, check, "notices")
}

#[cfg(test)]
mod tests {
    use super::{crates, stale_prose, table};

    const TREE: &str = "pklith v0.0.0 (/x/pklith)|MIT\nglobset v0.4.20|Unlicense OR MIT\nmemchr v2.8.3|Unlicense OR MIT\nglobset v0.4.20|Unlicense OR MIT (*)\nbroken line\n";

    #[test]
    fn crates_come_from_cargo_tree_once_each() {
        let got = crates(TREE);
        let names: Vec<&str> = got.iter().map(|(n, _, _)| n.as_str()).collect();
        assert_eq!(names, ["globset", "memchr"]);
        assert!(table(&got).contains("| globset | 0.4.20 | Unlicense OR MIT |\n"));
    }

    #[test]
    fn the_prose_is_held_to_the_table() {
        let set = crates(TREE);
        let doc = "ships **1 direct dependency**, which pulls in 2\ncrates in total.";
        assert!(stale_prose(doc, 1, &set).is_empty());
        assert_eq!(stale_prose(doc, 2, &set).len(), 1);
        let gpl = vec![("x".into(), "1".into(), "GPL-3.0".into())];
        let doc = "**2 direct dependencies**, which pulls in 1 crates";
        assert_eq!(
            stale_prose(doc, 2, &gpl),
            ["x is GPL-3.0, not available under MIT as docs/THIRD-PARTY-NOTICES.md says"]
        );
    }
}
