//! The seed files pklith can write, by the id a fragment's `seed` cell names
//! them with. Embedded in the binary (seed §C): seeding reads no network
//! and no clock.

/// What a seed id contributes.
pub enum Template {
    /// A whole file; `{name}` becomes the repository's directory name.
    File(&'static str, &'static str),
    /// A whole file written executable: a git hook.
    Script(&'static str, &'static str),
    /// Lines of `.gitignore`, which collects every active fragment's part.
    Ignore(&'static str),
}

/// Every seed id, in no particular order; fragment order decides output.
pub const TEMPLATES: [(&str, Template); 13] = [
    (
        "editorconfig",
        Template::File(".editorconfig", EDITORCONFIG),
    ),
    (
        "gitattributes",
        Template::File(".gitattributes", "* text=auto eol=lf\n"),
    ),
    ("readme", Template::File("README.md", "# {name}\n")),
    ("hk", Template::File("hk.pkl", HK)),
    ("hk-module", Template::File("hk.pklith.pkl", MODULE)),
    ("hk-schema", Template::File("pkl/Config.pkl", SCHEMA)),
    (
        "pre-commit",
        Template::Script(".githooks/pre-commit", PRE_COMMIT),
    ),
    ("pre-push", Template::Script(".githooks/pre-push", PRE_PUSH)),
    ("envrc", Template::File(".envrc", "use flake\n")),
    (
        "rubocop",
        Template::File(".rubocop.yml", "AllCops:\n  NewCops: enable\n"),
    ),
    (
        "ignore-nix",
        Template::Ignore(".direnv/\nresult\nresult-*\n"),
    ),
    ("ignore-rust", Template::Ignore("/target\n")),
    (
        "ignore-ruby",
        Template::Ignore("/vendor/bundle\n/.bundle\n"),
    ),
];

/// What editorconfig-checker (base fragment) holds files to: LF, UTF-8, a
/// final newline, no trailing blanks, spaces except where a tool needs a
/// tab. No indent width: languages differ, and their formatters own it.
const EDITORCONFIG: &str = "root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space

[{Makefile,*.mk,go.mod,*.go}]
indent_style = tab
";

/// The gate a fresh repository starts from: hk runs whatever
/// hk.pklith.pkl holds, which `pklith lay` fills one check per commit.
const HK: &str = r#"amends "pkl/Config.pkl"

// Seeded by `pklith seed`; yours to edit. The steps come from hk.pklith.pkl,
// which `pklith gen` and `pklith lay` write from .pklith: shape them here
// (excludes, depends) by amending a step by its id.
import "hk.pklith.pkl" as generated

local all = (generated.steps) { ...generated.push }

hooks {
  ["pre-commit"] {
    fix = true
    stash = "git"
    steps = generated.steps
  }
  ["pre-push"] {
    steps = all
  }
  ["check"] {
    steps = all
  }
  ["fix"] {
    fix = true
    steps = all
  }
}
"#;

/// What `pklith gen` writes for no checks, so hk.pkl evaluates before the
/// first check is laid.
pub const MODULE: &str = "// generated by `pklith gen` from .pklith; do not edit
import \"pkl/Config.pkl\"

steps: Mapping<String, Config.Step> = new {
}

push: Mapping<String, Config.Step> = new {
}
";

/// hk's schema, vendored so the gate evaluates offline (root V28).
const SCHEMA: &str = include_str!("../../pkl/Config.pkl");

/// Git hooks that hand the gate to hk and refuse when hk is missing: a
/// gate that cannot run has not passed (root V1).
const PRE_COMMIT: &str = "#!/usr/bin/env bash
# Seeded by `pklith seed`: the steps live in hk.pkl, this only makes them run.
# It refuses when hk is missing: a gate that cannot run has not passed.
set -e
if ! command -v hk >/dev/null 2>&1; then
  echo 'pre-commit REFUSED: hk is not on PATH, so nothing was checked.' >&2
  exit 1
fi
exec hk run pre-commit --from-hook \"$@\"
";

const PRE_PUSH: &str = "#!/usr/bin/env bash
# Seeded by `pklith seed`: the steps live in hk.pkl, this only makes them run.
# It refuses when hk is missing: a gate that cannot run has not passed.
set -e
if ! command -v hk >/dev/null 2>&1; then
  echo 'pre-push REFUSED: hk is not on PATH, so nothing was checked.' >&2
  exit 1
fi
exec hk run pre-push --from-hook \"$@\"
";

/// The template a seed id names.
#[must_use]
pub fn named(id: &str) -> Option<&'static Template> {
    TEMPLATES
        .iter()
        .find(|(name, _)| *name == id)
        .map(|(_, t)| t)
}
