#!/usr/bin/env bash
# The crate table in docs/THIRD-PARTY-NOTICES.md is a readable copy of what
# Cargo.lock resolves on normal (non-dev, non-build) dependency edges. The
# lock is the authority; this renders the table from it, so the copy cannot
# drift into a claim about crates pklith no longer ships.
#
#   scripts/notices.sh           rewrite the table in place
#   scripts/notices.sh --check   exit 1 when it differs from Cargo.lock
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
doc=docs/THIRD-PARTY-NOTICES.md

table() {
  local rows
  rows="$(cargo tree -e normal --prefix none -f '{p}|{l}' --locked --offline |
    sed 's/ (\*)//; s/ ([^)]*)$//; s/ (\/[^)]*)|/|/' | grep -v '^pklith ' | sort -u |
    awk -F'|' '{ split($1, p, " v"); printf "| %s | %s | %s |\n", p[1], p[2], $2 }')"
  [ -n "$rows" ] || { echo "notices: cargo tree listed no dependencies, so nothing was rendered" >&2; exit 1; }
  echo "<!-- BEGIN crates: generated by scripts/notices.sh from Cargo.lock; do not edit -->"
  echo "| Crate | Version | Licence |"
  echo "|---|---|---|"
  printf '%s\n' "$rows"
  echo "<!-- END crates -->"
}

render() {
  local generated
  generated="$(table)"
  awk -v gen="$generated" '
    /^<!-- BEGIN crates/ { print gen; skip = 1; found = 1; next }
    /^<!-- END crates -->/ { skip = 0; next }
    !skip { print }
    END { if (!found) exit 1 }
  ' "$doc"
}

out="$(render)" || { echo "notices: $doc has no <!-- BEGIN crates --> marker" >&2; exit 1; }

# The prose around the table states counts and a licence; hold it to them.
rows="$(printf '%s\n' "$out" | awk '/^<!-- BEGIN crates/{f=1; next} /^<!-- END crates/{f=0} f && /^\| [a-z]/')"
total="$(printf '%s\n' "$rows" | grep -c .)"
direct="$(awk 'f && /^[[]/ {exit} /^[[]dependencies[]]/ {f=1; next} f && /^[a-zA-Z0-9_.-]+ *=/ {n++} END {print n+0}' Cargo.toml)"
claim="$direct direct dependenc[a-z]*\*\*, which pulls in $total crates"
grep -Eq "\*\*$claim" "$doc" || { echo "notices: $doc must say **$direct direct dependency** and $total crates in its first paragraph" >&2; exit 1; }
if printf '%s\n' "$rows" | grep -v 'MIT' >&2; then
  echo "notices: a crate above is not available under MIT, so $doc's licence paragraph is wrong" >&2
  exit 1
fi
if [ "${1:-}" = --check ]; then
  if ! printf '%s\n' "$out" | diff -u "$doc" - >&2; then
    echo "notices: $doc no longer matches Cargo.lock. Run scripts/notices.sh, then check the prose around the table still holds." >&2
    exit 1
  fi
else
  printf '%s\n' "$out" >"$doc"
fi
