#!/usr/bin/env bash
# Regenerate the README badge block (root T43, V6), in the form the fleet's
# other open-source Rust repositories use (rekall, sherd, itok, microlith):
# a CI and a Rust group, a gate and spec group, a nix group, and credits.
#
# Every number is derived, and a badge's alt text and URL are filled from
# the same variable, so they cannot disagree. A source that reads empty or
# zero aborts the render: a badge is not worth a guessed number. The
# platform and "built with" badges stay literal on purpose: the platforms
# are editorial (intel and amd linux are one nix system), and the credits
# name what built this repository (every commit's Co-Authored-By trailer).
#
# --check: write nothing, exit 1 when README.md differs from its sources.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

badges() {
  local lic ed msrv deps cov inv bug nod com pus slug node nixref nixrev when nixday nixurl
  lic="$(sed -n 's/^license = "\(.*\)"/\1/p' Cargo.toml)"
  ed="$(sed -n 's/^edition = "\(.*\)"/\1/p' Cargo.toml)"
  msrv="$(sed -n 's/^rust-version = "\(.*\)"/\1/p' Cargo.toml)"
  deps="$(awk 'f && /^[[]/ {exit} /^[[]dependencies[]]/ {f=1; next} f && /^[a-zA-Z0-9_.-]+ *=/ {n++} END {print n+0}' Cargo.toml)"
  cov="$(sed -n 's/^lines \([0-9.]*\)$/\1/p' .coverage | sed 's/\.00$//')"
  # Rows, not distinct ids: every node numbers its own from V1 and B1, so
  # distinct ids would count one per number, not one per invariant.
  inv="$(git ls-files '*SPEC.md' | xargs cat | grep -cE '^V[0-9]+:')"
  bug="$(git ls-files '*SPEC.md' | xargs cat | grep -cE '^B[0-9]+[|]')"
  nod="$(git ls-files '*SPEC.md' | wc -l | tr -d ' ')"
  com="$(pkl eval --format json hk.pkl | jq '.hooks["pre-commit"].steps | length')"
  pus="$(pkl eval --format json hk.pkl | jq '.hooks["pre-push"].steps | length')"
  slug="$(sed -n 's|^repository = "https://github.com/\(.*\)"|\1|p' Cargo.toml)"
  # The nixpkgs pklith builds with, from the lock: the branch in flake.nix
  # says which series, the lock says which commit.
  node="$(awk '/^    "nixpkgs": [{]/{f=1} f{print} f && /^    [}],?$/{exit}' flake.lock)"
  nixref="$(printf '%s' "$node" | grep -m1 '"ref"' | cut -d'"' -f4 | sed 's/^nixos-//')"
  nixrev="$(printf '%s' "$node" | grep -m1 '"rev"' | cut -d'"' -f4 | cut -c1-7)"
  when="$(printf '%s' "$node" | grep -m1 '"lastModified"' | tr -dc '0-9')"
  nixday="$(date -u -r "$when" +%Y-%m-%d 2>/dev/null || date -u -d "@$when" +%Y-%m-%d)"
  # shields.io reads one dash as a separator, so the date doubles its own.
  nixurl="${nixday//-/--}"
  grep -q '^unsafe_code = "forbid"' Cargo.toml || {
    echo "readme-badges: Cargo.toml no longer forbids unsafe code, so the badge would lie" >&2
    exit 1
  }
  for v in "$lic" "$ed" "$msrv" "$deps" "$cov" "$inv" "$bug" "$nod" "$com" "$pus" "$slug" "$nixref" "$nixrev" "$nixday"; do
    case "$v" in '' | 0)
      echo "readme-badges: a badge source read empty or zero (Cargo.toml, .coverage, the SPEC.md set, hk.pkl or flake.lock); fix the source, a badge is not worth a guess" >&2
      exit 1
      ;;
    esac
  done
  cat <<BADGES
<!-- BEGIN badges: generated by scripts/readme-badges.sh; do not edit -->
[![CI](https://github.com/$slug/actions/workflows/ci.yml/badge.svg)](https://github.com/$slug/actions/workflows/ci.yml)
[![License: $lic](https://img.shields.io/badge/license-$lic-blue.svg)](LICENSE)
[![edition $ed](https://img.shields.io/badge/edition-$ed-000000?logo=rust&logoColor=white)](Cargo.toml)
[![MSRV $msrv](https://img.shields.io/badge/MSRV-$msrv-000000?logo=rust&logoColor=white)](Cargo.toml)
[![direct dependencies $deps](https://img.shields.io/badge/direct_dependencies-$deps-brightgreen)](docs/THIRD-PARTY-NOTICES.md)
[![unsafe forbidden](https://img.shields.io/badge/unsafe-forbidden-brightgreen)](Cargo.toml)
[![network pkli protect only](https://img.shields.io/badge/network-pkli_protect_only-brightgreen)](SECURITY.md)

[![gate hk](https://img.shields.io/badge/gate-hk-6E4AFF)](hk.pkl)
[![gate steps $com commit / $pus push](https://img.shields.io/badge/gate_steps-${com}_commit_%2F_${pus}_push-6E4AFF)](hk.pkl)
[![coverage floor $cov%](https://img.shields.io/badge/coverage_floor-%E2%89%A5$cov%25-brightgreen)](.coverage)
[![invariants $inv](https://img.shields.io/badge/invariants-$inv-6E4AFF)](SPEC.md)
[![bugs logged $bug](https://img.shields.io/badge/bugs_logged-$bug-6E4AFF)](SPEC.md)
[![federated nodes $nod](https://img.shields.io/badge/federated_nodes-$nod-6E4AFF)](SPEC.md)

[![nix flake](https://img.shields.io/badge/nix-flake-5277C3?logo=nixos&logoColor=white)](flake.nix)
[![nixpkgs $nixref ($nixday - $nixrev)](https://img.shields.io/badge/nixpkgs-${nixref}_(${nixurl}_--_${nixrev})-5277C3?logo=nixos&logoColor=white)](flake.lock)
[![intel linux](https://img.shields.io/badge/linux-5277C3?logo=intel&logoColor=white)](flake.nix)
[![amd linux](https://img.shields.io/badge/linux-5277C3?logo=amd&logoColor=white)](flake.nix)
[![arm linux](https://img.shields.io/badge/linux-5277C3?logo=arm&logoColor=white)](flake.nix)
[![arm macos](https://img.shields.io/badge/macos-5277C3?logo=arm&logoColor=white)](flake.nix)

[![built with Claude Code](https://img.shields.io/badge/built_with-Claude_Code-D97757)](https://claude.com/claude-code)
[![built with Opus 5.5](https://img.shields.io/badge/built_with-Opus_5.5-D97757)](https://www.anthropic.com/claude)
[![built with SDD](https://img.shields.io/badge/built_with-spec--driven_development-D97757)](SPEC.md)
<!-- END badges -->
BADGES
}

render() {
  local generated
  generated="$(badges)"
  awk -v gen="$generated" '
    /^<!-- BEGIN badges/ { print gen; skip = 1; found = 1; next }
    /^<!-- END badges -->/ { skip = 0; next }
    !skip { print }
    END { if (!found) exit 1 }
  ' README.md
}

if [ "${1:-}" = --check ]; then
  if ! render | diff -u README.md - >&2; then
    echo "readme-badges: README.md badges no longer match the repository. Run scripts/readme-badges.sh and stage the result." >&2
    exit 1
  fi
else
  out="$(render)" || { echo "readme-badges: README.md has no <!-- BEGIN badges --> marker" >&2; exit 1; }
  printf '%s\n' "$out" > README.md
fi
