#!/usr/bin/env bash
# Regenerate the README badges from what the repository says (root T43, V6):
# the license and MSRV from Cargo.toml, the coverage floor from .coverage,
# the gate's step count from hk.pkl. A badge typed by hand drifts from the
# fact it shows; this one cannot.
# --check: write nothing, exit 1 when README.md differs from those facts.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# shields.io path escaping: `-` doubles, `%` and `+` are encoded.
esc() {
  printf '%s' "$1" | sed 's/-/--/g; s/%/%25/g; s/+/%2B/g; s/ /%20/g'
}

badge() {
  printf '![%s: %s](https://img.shields.io/badge/%s-%s-%s)' "$1" "$2" "$(esc "$1")" "$(esc "$2")" "$3"
}

badges() {
  local license msrv floor steps
  license="$(sed -n 's/^license = "\(.*\)"/\1/p' Cargo.toml)"
  msrv="$(sed -n 's/^rust-version = "\(.*\)"/\1/p' Cargo.toml)"
  floor="$(sed -n 's/^lines \([0-9.]*\)$/\1/p' .coverage | sed 's/\.00$//')"
  steps="$(pkl eval --format json hk.pkl | jq '.hooks["pre-push"].steps | length')"
  [ -n "$license" ] && [ -n "$msrv" ] && [ -n "$floor" ] && [ -n "$steps" ] || {
    echo "readme-badges: a fact is missing (license '$license', rust-version '$msrv', .coverage floor '$floor', steps '$steps')" >&2
    exit 1
  }
  echo "<!-- BEGIN badges: generated by scripts/readme-badges.sh; do not edit -->"
  printf '%s\n' "$(badge license "$license" blue) $(badge rust "$msrv+" orange) $(badge "coverage floor" "$floor%" brightgreen) $(badge gate "$steps steps" informational)"
  echo "<!-- END badges -->"
}

render() {
  local generated
  generated="$(badges)"
  awk -v gen="$generated" '
    /^<!-- BEGIN badges/ { print gen; skip = 1; found = 1; next }
    /^<!-- END badges -->/ { skip = 0; next }
    !skip { print }
    END { if (!found) exit 1 }
  ' README.md
}

if [ "${1:-}" = --check ]; then
  if ! render | diff -u README.md - >&2; then
    echo "readme-badges: README.md badges no longer match the repository. Run scripts/readme-badges.sh and stage the result." >&2
    exit 1
  fi
else
  out="$(render)" || { echo "readme-badges: README.md has no <!-- BEGIN badges --> marker" >&2; exit 1; }
  printf '%s\n' "$out" > README.md
fi
