//! The verdict (`src/cover/SPEC.md`): which file types lack checks, which
//! declarations match nothing, which types are exempt. A pure function over
//! scanned paths and a parsed registry.

use crate::registry::{Registry, TypeRow};
use crate::scan::{Globs, candidates};

mod claims;
mod staged;
pub use claims::{Unbacked, claimed_somewhere, claims_any, unbacked};
pub use staged::judge_staged;

/// A type found on disk with no registry row (V1, V6): every file is
/// judged, none silently dropped.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Gap {
    /// Key to declare: the least specific candidate, the one the legacy tools
    /// keyed on.
    pub key: String,
    /// Files of that type, sorted.
    pub files: Vec<String>,
}

/// A declared type that no file resolves to (V2). A `path:` class counts
/// here until path classes are matched, so it fails loudly instead of being
/// ignored.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stale {
    /// The declared key.
    pub key: String,
    /// Its line in `.pklith`.
    pub line: usize,
}

/// A declared type and how many files it covers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Covered {
    /// The declared key.
    pub key: String,
    /// Files resolved to it.
    pub files: usize,
    /// The exemption reason, when the type is exempt (V4).
    pub exempt: Option<String>,
}

/// Coverage of one tree against one registry.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Coverage {
    /// Types on disk with no row.
    pub gaps: Vec<Gap>,
    /// Rows matching no file.
    pub stale: Vec<Stale>,
    /// Rows matching files, checked or exempt.
    pub covered: Vec<Covered>,
    /// Companion rules a file fails (V7).
    pub failed: Vec<crate::rule::Failure>,
}

impl Coverage {
    /// The gate verdict: no gap, nothing stale, no failed rule. An empty
    /// tree passes (V5).
    #[must_use]
    pub fn ok(&self) -> bool {
        self.gaps.is_empty() && self.stale.is_empty() && self.failed.is_empty()
    }
}

/// Judge `files` against `registry`.
#[must_use]
pub fn judge(files: &[String], registry: &Registry) -> Coverage {
    let declared: Vec<&TypeRow> = registry.types.iter().filter(|t| t.key != "*").collect();
    let classes = classes(&declared);
    let mut coverage = Coverage::default();
    let mut counts = vec![0usize; declared.len()];
    for file in files {
        match resolve(file, &declared, &classes) {
            Some(i) => counts.get_mut(i).into_iter().for_each(|n| *n += 1),
            None => gap(&mut coverage.gaps, file),
        }
    }
    for (row, files) in declared.into_iter().zip(counts) {
        tally(&mut coverage, row, files);
    }
    coverage
}

/// Index of the declared type a file resolves to (scan V1): the most specific
/// path class that matches, else its first basename candidate that is
/// declared.
fn resolve(file: &str, declared: &[&TypeRow], classes: &[(usize, Globs)]) -> Option<usize> {
    let class = classes
        .iter()
        .find(|(_, globs)| globs.matches(file))
        .map(|(i, _)| *i);
    class.or_else(|| {
        candidates(file)
            .iter()
            .find_map(|c| declared.iter().position(|t| t.key == c.key))
    })
}

/// `path:<glob>` rows, most specific first: longest literal prefix, then
/// declaration order. A glob that does not compile never matches; the
/// registry already refused it with its line.
fn classes(declared: &[&TypeRow]) -> Vec<(usize, Globs)> {
    let compile = |(i, t): (usize, &&TypeRow)| {
        let glob = t.key.strip_prefix("path:")?;
        Some((
            literal_prefix(glob),
            i,
            Globs::new(&[glob.to_owned()]).ok()?,
        ))
    };
    let mut classes: Vec<(usize, usize, Globs)> =
        declared.iter().enumerate().filter_map(compile).collect();
    classes.sort_by(|a, b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
    classes
        .into_iter()
        .map(|(_, i, globs)| (i, globs))
        .collect()
}

fn literal_prefix(glob: &str) -> usize {
    glob.find(['*', '?', '[', '{']).unwrap_or(glob.len())
}

fn gap(gaps: &mut Vec<Gap>, file: &str) {
    let key = crate::scan::key(file);
    match gaps.iter_mut().find(|g| g.key == key) {
        Some(g) => g.files.push(file.to_owned()),
        None => gaps.push(Gap {
            key,
            files: vec![file.to_owned()],
        }),
    }
}

fn tally(coverage: &mut Coverage, row: &TypeRow, files: usize) {
    if files == 0 {
        coverage.stale.push(Stale {
            key: row.key.clone(),
            line: row.line,
        });
    } else {
        coverage.covered.push(Covered {
            key: row.key.clone(),
            files,
            exempt: row.exempt.clone(),
        });
    }
}

#[cfg(test)]
mod tests {
    use super::{Coverage, Covered, judge};
    use crate::registry::{Error, parse};

    const REGISTRY: &str = "format 1\n## types\ntype|checks|min|exempt\n*|typos|-|-\nrs|clippy|-|-\nCargo.lock|-|-|generated by cargo\nlock|lockcheck|-|-\npy|ruff|-|-\n";

    fn files(names: &[&str]) -> Vec<String> {
        names.iter().map(|n| (*n).to_owned()).collect()
    }

    fn covered(key: &str, files: usize, exempt: Option<&str>) -> Covered {
        Covered {
            key: key.to_owned(),
            files,
            exempt: exempt.map(str::to_owned),
        }
    }

    /// The most specific declared candidate wins (scan V1): Cargo.lock is
    /// its own exempt type, flake.lock falls to `lock` (V4: exempt is
    /// covered and reported with its reason).
    #[test]
    fn each_file_resolves_to_its_most_specific_declared_type() -> Result<(), Error> {
        let coverage = judge(
            &files(&["src/a.rs", "src/b.rs", "Cargo.lock", "flake.lock"]),
            &parse(REGISTRY)?,
        );
        let want = [
            covered("rs", 2, None),
            covered("Cargo.lock", 1, Some("generated by cargo")),
            covered("lock", 1, None),
        ];
        assert_eq!(coverage.covered, want);
        Ok(())
    }

    /// V1, V6: a type with no row is a gap listing every file, keyed as the
    /// legacy tools did; `*` alone does not declare a type.
    #[test]
    fn undeclared_types_are_gaps() -> Result<(), Error> {
        let coverage = judge(
            &files(&["a.rs", "x/t.tar.gz", "y.gz", "Makefile"]),
            &parse(REGISTRY)?,
        );
        let gaps: Vec<String> = coverage
            .gaps
            .iter()
            .map(|g| format!("{} {:?}", g.key, g.files))
            .collect();
        assert_eq!(
            gaps,
            [r#"gz ["x/t.tar.gz", "y.gz"]"#, r#"Makefile ["Makefile"]"#]
        );
        Ok(())
    }

    /// V2: a declared row that no file resolves to is stale, with its line.
    #[test]
    fn unused_rows_are_stale() -> Result<(), Error> {
        let coverage = judge(&files(&["a.rs"]), &parse(REGISTRY)?);
        let stale: Vec<(&str, usize)> = coverage
            .stale
            .iter()
            .map(|s| (s.key.as_str(), s.line))
            .collect();
        assert_eq!(stale, [("Cargo.lock", 6), ("lock", 7), ("py", 8)]);
        Ok(())
    }

    /// V5: an empty tree against an empty registry passes; any gap or stale
    /// row fails.
    #[test]
    fn the_verdict_needs_no_gap_and_nothing_stale() -> Result<(), Error> {
        assert!(judge(&[], &parse("format 1")?).ok());
        assert!(!judge(&files(&["a.rs"]), &parse("format 1")?).ok());
        assert!(!judge(&[], &parse(REGISTRY)?).ok());
        assert!(Coverage::default().ok());
        Ok(())
    }
}

#[cfg(test)]
mod path_tests {
    use super::judge;
    use crate::registry::{Error, parse};

    const CLASSES: &str = "format 1\n## types\ntype|checks|min|exempt\nmd|lint|-|-\npath:vendor/**|-|-|vendored verbatim\npath:vendor/keep/**|lint|-|-\npath:a/*.md|lint|-|-\npath:a/*|lint|-|-\npath:nothing/**|lint|-|-\n";

    fn resolved(files: &[&str]) -> Result<Vec<String>, Error> {
        let files: Vec<String> = files.iter().map(|f| (*f).to_owned()).collect();
        let coverage = judge(&files, &parse(CLASSES)?);
        let mut out: Vec<String> = coverage
            .covered
            .iter()
            .map(|c| format!("{} {}", c.key, c.files))
            .collect();
        out.extend(coverage.stale.iter().map(|s| format!("stale {}", s.key)));
        Ok(out)
    }

    /// scan V1: a path class beats any basename type; the longest literal
    /// prefix wins whatever the order; a tie goes to the first declared.
    #[test]
    fn the_most_specific_path_class_wins() -> Result<(), Error> {
        let got = resolved(&["README.md", "vendor/a.md", "vendor/keep/b.md", "a/x.md"])?;
        let want = [
            "md 1",
            "path:vendor/** 1",
            "path:vendor/keep/** 1",
            "path:a/*.md 1",
            "stale path:a/*",
            "stale path:nothing/**",
        ];
        assert_eq!(got, want);
        Ok(())
    }
}
