//! The verdict (`src/cover/SPEC.md`): which file types lack checks, which
//! declarations match nothing, which types are exempt. A pure function over
//! scanned paths and a parsed registry.

use crate::registry::{Registry, TypeRow};
use crate::scan::candidates;

/// A type found on disk with no registry row (V1, V6): every file is
/// judged, none silently dropped.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Gap {
    /// Key to declare: the least specific candidate, the one the legacy tools
    /// keyed on.
    pub key: String,
    /// Files of that type, sorted.
    pub files: Vec<String>,
}

/// A declared type that no file resolves to (V2). A `path:` class counts
/// here until path classes are matched, so it fails loudly instead of being
/// ignored.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stale {
    /// The declared key.
    pub key: String,
    /// Its line in `.pklith`.
    pub line: usize,
}

/// A declared type and how many files it covers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Covered {
    /// The declared key.
    pub key: String,
    /// Files resolved to it.
    pub files: usize,
    /// The exemption reason, when the type is exempt (V4).
    pub exempt: Option<String>,
}

/// Coverage of one tree against one registry.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Coverage {
    /// Types on disk with no row.
    pub gaps: Vec<Gap>,
    /// Rows matching no file.
    pub stale: Vec<Stale>,
    /// Rows matching files, checked or exempt.
    pub covered: Vec<Covered>,
}

impl Coverage {
    /// The gate verdict: no gap and nothing stale. An empty tree passes (V5).
    #[must_use]
    pub fn ok(&self) -> bool {
        self.gaps.is_empty() && self.stale.is_empty()
    }
}

/// Judge `files` against `registry`.
#[must_use]
pub fn judge(files: &[String], registry: &Registry) -> Coverage {
    let declared: Vec<&TypeRow> = registry.types.iter().filter(|t| t.key != "*").collect();
    let mut coverage = Coverage::default();
    let mut counts = vec![0usize; declared.len()];
    for file in files {
        match resolve(file, &declared) {
            Some(i) => counts.get_mut(i).into_iter().for_each(|n| *n += 1),
            None => gap(&mut coverage.gaps, file),
        }
    }
    for (row, files) in declared.into_iter().zip(counts) {
        tally(&mut coverage, row, files);
    }
    coverage
}

/// Index of the declared type a file resolves to: its first candidate that
/// is declared (scan V1).
fn resolve(file: &str, declared: &[&TypeRow]) -> Option<usize> {
    candidates(file)
        .iter()
        .find_map(|c| declared.iter().position(|t| t.key == c.key))
}

fn gap(gaps: &mut Vec<Gap>, file: &str) {
    let key = candidates(file).pop().map(|c| c.key).unwrap_or_default();
    match gaps.iter_mut().find(|g| g.key == key) {
        Some(g) => g.files.push(file.to_owned()),
        None => gaps.push(Gap {
            key,
            files: vec![file.to_owned()],
        }),
    }
}

fn tally(coverage: &mut Coverage, row: &TypeRow, files: usize) {
    if files == 0 {
        coverage.stale.push(Stale {
            key: row.key.clone(),
            line: row.line,
        });
    } else {
        coverage.covered.push(Covered {
            key: row.key.clone(),
            files,
            exempt: row.exempt.clone(),
        });
    }
}

#[cfg(test)]
mod tests {
    use super::{Coverage, Covered, judge};
    use crate::registry::{Error, parse};

    const REGISTRY: &str = "format 1\n## types\ntype|checks|min|exempt\n*|typos|-|-\nrs|clippy|-|-\nCargo.lock|-|-|generated by cargo\nlock|lockcheck|-|-\npy|ruff|-|-\n";

    fn files(names: &[&str]) -> Vec<String> {
        names.iter().map(|n| (*n).to_owned()).collect()
    }

    fn covered(key: &str, files: usize, exempt: Option<&str>) -> Covered {
        Covered {
            key: key.to_owned(),
            files,
            exempt: exempt.map(str::to_owned),
        }
    }

    /// The most specific declared candidate wins (scan V1): Cargo.lock is
    /// its own exempt type, flake.lock falls to `lock` (V4: exempt is
    /// covered and reported with its reason).
    #[test]
    fn each_file_resolves_to_its_most_specific_declared_type() -> Result<(), Error> {
        let coverage = judge(
            &files(&["src/a.rs", "src/b.rs", "Cargo.lock", "flake.lock"]),
            &parse(REGISTRY)?,
        );
        let want = [
            covered("rs", 2, None),
            covered("Cargo.lock", 1, Some("generated by cargo")),
            covered("lock", 1, None),
        ];
        assert_eq!(coverage.covered, want);
        Ok(())
    }

    /// V1, V6: a type with no row is a gap listing every file, keyed as the
    /// legacy tools did; `*` alone does not declare a type.
    #[test]
    fn undeclared_types_are_gaps() -> Result<(), Error> {
        let coverage = judge(
            &files(&["a.rs", "x/t.tar.gz", "y.gz", "Makefile"]),
            &parse(REGISTRY)?,
        );
        let gaps: Vec<String> = coverage
            .gaps
            .iter()
            .map(|g| format!("{} {:?}", g.key, g.files))
            .collect();
        assert_eq!(
            gaps,
            [r#"gz ["x/t.tar.gz", "y.gz"]"#, r#"Makefile ["Makefile"]"#]
        );
        Ok(())
    }

    /// V2: a declared row that no file resolves to is stale, with its line.
    #[test]
    fn unused_rows_are_stale() -> Result<(), Error> {
        let coverage = judge(&files(&["a.rs"]), &parse(REGISTRY)?);
        let stale: Vec<(&str, usize)> = coverage
            .stale
            .iter()
            .map(|s| (s.key.as_str(), s.line))
            .collect();
        assert_eq!(stale, [("Cargo.lock", 6), ("lock", 7), ("py", 8)]);
        Ok(())
    }

    /// V5: an empty tree against an empty registry passes; any gap or stale
    /// row fails.
    #[test]
    fn the_verdict_needs_no_gap_and_nothing_stale() -> Result<(), Error> {
        assert!(judge(&[], &parse("format 1")?).ok());
        assert!(!judge(&files(&["a.rs"]), &parse("format 1")?).ok());
        assert!(!judge(&[], &parse(REGISTRY)?).ok());
        assert!(Coverage::default().ok());
        Ok(())
    }
}
